pipeline {
   agent any

    properties([
            parameters(
                [   
                    string(defaultValue: '', description: 'Azure Account Username', name: 'azure_username'),
                    string(defaultValue: '', description: 'Azure Tenant', name: 'azure_tenant'), 
                    password(defaultValue: '', description: 'Azure Account Password', name: 'azure_password'),
                    string(defaultValue: '', description: 'FTP Account Username', name: 'ftp_user'),
                    password(defaultValue: '', description: 'FTP Account Password', name: 'ftp_passwd'),
                    string(defaultValue: '', description: 'FTP Host', name: 'ftp_host'),
                    string(defaultValue: '', description: 'FTP Remote Dir', name: 'ftp_remote_dir')
                ]
            ), 
            pipelineTriggers([])
        ])
 
    stage ('Creating infrastructure with Azure Template') {
        git branch: 'master', url: 'https://github.com/evangelism/DevTest.git'
        dir('AzureRG/jenkins-ci/') {
          sh "./deploy-template.sh ${params.azure_username} ${params.azure_password} ${params.azure_tenant}"
        }
    }

    stage ('Publishing Sample App') {
            dir('SampleApp') {
                git branch: 'master', url: 'https://github.com/easkerov/DotNetSampleAppBinaries.git'
                sh "rm -rf .git"
                sh "wput --basename=$(pwd) ftp://${params.ftp_user}:${params.ftp_passwd}@${params.ftp_host}${params.ftp_remote_dir}"  
        }
    }
}